# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(111, 165)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.deep_work_button = QtWidgets.QPushButton(Form)
        self.deep_work_button.setObjectName("deep_work_button")
        self.gridLayout.addWidget(self.deep_work_button, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.paper_button = QtWidgets.QPushButton(Form)
        self.paper_button.setObjectName("paper_button")
        self.gridLayout.addWidget(self.paper_button, 4, 0, 1, 1)
        self.deep_work_label = QtWidgets.QLabel(Form)
        self.deep_work_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.deep_work_label.setText("")
        self.deep_work_label.setScaledContents(False)
        self.deep_work_label.setAlignment(QtCore.Qt.AlignCenter)
        self.deep_work_label.setObjectName("deep_work_label")
        self.gridLayout.addWidget(self.deep_work_label, 1, 0, 1, 1)
        self.daily_setup_button = QtWidgets.QPushButton(Form)
        self.daily_setup_button.setObjectName("daily_setup_button")
        self.gridLayout.addWidget(self.daily_setup_button, 3, 0, 1, 1)
        self.independent_study_button = QtWidgets.QPushButton(Form)
        self.independent_study_button.setObjectName("independent_study_button")
        self.gridLayout.addWidget(self.independent_study_button, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.deep_work_button.setText(_translate("Form", "Start deep work timer"))
        self.paper_button.setText(_translate("Form", "Paper reading"))
        self.daily_setup_button.setText(_translate("Form", "Daily setup"))
        self.independent_study_button.setText(_translate("Form", "Independent study"))
