# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(216, 95)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.daily_setup_button = QtWidgets.QPushButton(Form)
        self.daily_setup_button.setObjectName("daily_setup_button")
        self.gridLayout.addWidget(self.daily_setup_button, 1, 0, 1, 1)
        self.deep_work_label = QtWidgets.QLabel(Form)
        self.deep_work_label.setText("")
        self.deep_work_label.setScaledContents(False)
        self.deep_work_label.setAlignment(QtCore.Qt.AlignCenter)
        self.deep_work_label.setObjectName("deep_work_label")
        self.gridLayout.addWidget(self.deep_work_label, 2, 1, 1, 1)
        self.deep_work_button = QtWidgets.QPushButton(Form)
        self.deep_work_button.setObjectName("deep_work_button")
        self.gridLayout.addWidget(self.deep_work_button, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.daily_setup_button.setText(_translate("Form", "Daily setup"))
        self.deep_work_button.setText(_translate("Form", "Start timer"))
