# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(164, 235)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.write_flash_cards_button = QtWidgets.QPushButton(Form)
        self.write_flash_cards_button.setObjectName("write_flash_cards_button")
        self.gridLayout.addWidget(self.write_flash_cards_button, 9, 0, 1, 1)
        self.work_button = QtWidgets.QPushButton(Form)
        self.work_button.setObjectName("work_button")
        self.gridLayout.addWidget(self.work_button, 2, 0, 1, 1)
        self.daily_setup_button = QtWidgets.QPushButton(Form)
        self.daily_setup_button.setObjectName("daily_setup_button")
        self.gridLayout.addWidget(self.daily_setup_button, 0, 0, 1, 1)
        self.paper_button = QtWidgets.QPushButton(Form)
        self.paper_button.setObjectName("paper_button")
        self.gridLayout.addWidget(self.paper_button, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.work_label = QtWidgets.QLabel(Form)
        self.work_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.work_label.setText("")
        self.work_label.setScaledContents(False)
        self.work_label.setAlignment(QtCore.Qt.AlignCenter)
        self.work_label.setObjectName("work_label")
        self.gridLayout.addWidget(self.work_label, 5, 0, 1, 1)
        self.add_flash_cards_button = QtWidgets.QPushButton(Form)
        self.add_flash_cards_button.setObjectName("add_flash_cards_button")
        self.gridLayout.addWidget(self.add_flash_cards_button, 10, 0, 1, 1)
        self.stop_work_button = QtWidgets.QPushButton(Form)
        self.stop_work_button.setObjectName("stop_work_button")
        self.gridLayout.addWidget(self.stop_work_button, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.write_flash_cards_button.setText(_translate("Form", "Write flash cards"))
        self.work_button.setText(_translate("Form", "Start work timer"))
        self.daily_setup_button.setText(_translate("Form", "Daily setup"))
        self.paper_button.setText(_translate("Form", "Paper reading"))
        self.add_flash_cards_button.setText(_translate("Form", "Add flash cards"))
        self.stop_work_button.setText(_translate("Form", "Stop work timer"))
