# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/paper_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.paper_title_label = QtWidgets.QLabel(Form)
        self.paper_title_label.setObjectName("paper_title_label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.paper_title_label
        )
        self.paper_author_label = QtWidgets.QLabel(Form)
        self.paper_author_label.setObjectName("paper_author_label")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.paper_author_label
        )
        self.paper_year_label = QtWidgets.QLabel(Form)
        self.paper_year_label.setObjectName("paper_year_label")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.paper_year_label
        )
        self.paper_title_line_edit = QtWidgets.QLineEdit(Form)
        self.paper_title_line_edit.setObjectName("paper_title_line_edit")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.paper_title_line_edit
        )
        self.paper_author_line_edit = QtWidgets.QLineEdit(Form)
        self.paper_author_line_edit.setObjectName("paper_author_line_edit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.paper_author_line_edit
        )
        self.paper_year_line_edit = QtWidgets.QLineEdit(Form)
        self.paper_year_line_edit.setObjectName("paper_year_line_edit")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.paper_year_line_edit
        )
        self.done_button = QtWidgets.QPushButton(Form)
        self.done_button.setObjectName("done_button")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.SpanningRole, self.done_button
        )
        self.field_label = QtWidgets.QLabel(Form)
        self.field_label.setObjectName("field_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.field_label)
        self.field_line_edit = QtWidgets.QLineEdit(Form)
        self.field_line_edit.setObjectName("field_line_edit")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.field_line_edit
        )
        self.subfield_label = QtWidgets.QLabel(Form)
        self.subfield_label.setObjectName("subfield_label")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.subfield_label
        )
        self.subfield_line_edit = QtWidgets.QLineEdit(Form)
        self.subfield_line_edit.setObjectName("subfield_line_edit")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.subfield_line_edit
        )

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.paper_title_label.setText(_translate("Form", "Title"))
        self.paper_author_label.setText(_translate("Form", "Author"))
        self.paper_year_label.setText(_translate("Form", "Year"))
        self.done_button.setText(_translate("Form", "Done"))
        self.field_label.setText(_translate("Form", "Field"))
        self.subfield_label.setText(_translate("Form", "Subfield"))
