# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/paper_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.paper_uri_label = QtWidgets.QLabel(Form)
        self.paper_uri_label.setObjectName("paper_uri_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.paper_uri_label)
        self.paper_uri_line_edit = QtWidgets.QLineEdit(Form)
        self.paper_uri_line_edit.setObjectName("paper_uri_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paper_uri_line_edit)
        self.done_button = QtWidgets.QPushButton(Form)
        self.done_button.setAutoDefault(True)
        self.done_button.setDefault(True)
        self.done_button.setObjectName("done_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.done_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.paper_uri_label.setText(_translate("Form", "URI"))
        self.done_button.setText(_translate("Form", "Done"))
